-- show db contents
select 'sizes' from pizza_sys_tab;
select * from sizes;
select 'toppings' from pizza_sys_tab;
select * from toppings;
select 'pizza_orders' from pizza_sys_tab;
select * from pizza_orders;
select 'order_topping' from pizza_sys_tab;
select * from order_topping;
select 'status_values' from pizza_sys_tab;
select * from status_values;
select 'pizza_sys_tab' from pizza_sys_tab;
select * from pizza_sys_tab;